### ISSUE TITLE
Help, how to compile?

### ISSUE THREAD

**Issue by yoricya** [badjr/JavaOS#1]
Help, how to compile?

**Comment by badjr** [comment]
Hello @imyoric,

You can compile by going to the **src** directory and running `javac minikernel/*.java main/*.java`. This will compile all the java files in the **minikernel** and **main** directories.

Then you can run the program by running `java main.Main` from the **src** directory.

Does this work for you?

**Comment by yoricya** [comment]
Thank you! It works!
